nodeLinker: node-modules
unsafeHttpWhitelist:
  - "npm.greensock.com"
npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "76C3DC2A-E980-486B-A485-12F7991E7BEE"
  awesome.me:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "76C3DC2A-E980-486B-A485-12F7991E7BEE"
  gsap:
    npmRegistryServer: "https://npm.greensock.com"
    npmAuthToken: 69479865-b3e0-4b3b-9e6b-ae168da44e55
