nodeLinker: node-modules
npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "76C3DC2A-E980-486B-A485-12F7991E7BEE"
  awesome.me:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "76C3DC2A-E980-486B-A485-12F7991E7BEE"
